/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import hexlet.code.games.*;

public class App {
    public static void main(String[] args) {
        int choice = Cli.playerChoice();
        int result;
        final int maxInputNumber = 6;

        if (choice == 0) {
            return;
        } else if (choice < 0 || choice > maxInputNumber) {
            System.out.println("If you fail this step, brain games aren't your cup of tea");
            return;
        }

        System.out.println("Welcome to the Brain Games!");
        String playerName = Cli.getPlayerName();
        System.out.println("Hello, " + playerName + "!");
        Game gameChoosenByPlayer;
        switch (choice) {
            case 1:
                return;
            case 2:
                gameChoosenByPlayer = new Even();
                break;
            case 3:
                gameChoosenByPlayer = new Calculator();
                break;
            case 4: 
                gameChoosenByPlayer = new GCD();
                break;
            default:
                return;
        }
        Engine currentGame = new Engine(gameChoosenByPlayer);
        result = currentGame.gameProcess();
        if (result == 0) { //success
            System.out.println("Congratulations, " + playerName);
        } else { //fail
            System.out.println("Let's try again, " + playerName);
        }
    }
}
