/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

public class App {
    public static void main(String[] args) {
        int choice = Engine.getPlayersChoice();
        int result;
        final int maxInputNumber = 6;
        if (choice <= 0 || choice > maxInputNumber) {
            return;
        }

        String playerName = Engine.greetPlayer();
        result = Engine.gameDistrubute(choice);
        Engine.gameEnd(result, playerName);
    }
}
