/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;
import static hexlet.code.games.Even.startEvenGame;
import static hexlet.code.games.GCD.startGCDGame;
import static hexlet.code.games.Calculator.startCalculatorGame;
import static hexlet.code.games.Prime.startPrimeGame;
import static hexlet.code.games.Progression.startProgressionGame;

public class App {
    public static void main(String[] args) {
        int game = Cli.playerChoice();
        final int maxInputNumber = 6;
        if (game <= 0 || game > maxInputNumber) {
            return;
        }

        final int choiceGreet = 1;
        final int choiceEven = 2;
        final int choiceCalc = 3;
        final int choiceGCD = 4;
        final int choiceProgression = 5;
        final int choicePrime = 6;
        final int numberOfRounds = 3;

        switch (game) {
            case choiceGreet:
                System.out.println("Welcome to the Brain Games!");
                String player = Cli.getPlayerName();
                System.out.println("Hello, " + player + "!");
                break;
            case choiceEven:
                startEvenGame(numberOfRounds);
                break;
            case choiceCalc:
                startCalculatorGame(numberOfRounds);
                break;
            case choiceGCD:
                startGCDGame(numberOfRounds);
                break;
            case choiceProgression:
                startProgressionGame(numberOfRounds);
                break;
            case choicePrime:
                startPrimeGame(numberOfRounds);
                break;
            default:
                break;
        }
        return;
    }
}
